### ISSUE TITLE
[BUG] Using * as rule does not produce correct output

### ISSUE THREAD

**Issue by faebeee** [RockiRider/csp#50]
**Describe the bug**
Using a policy with `['*']` results in the wrong format

**Expected behaviour**
config `'frame-src': ['*'],` should result in `frame-src: *`. Currently it results in `frame-src: '*'` which is invalid

**Screenshots**
![Screenshot 2024-10-03 at 10 37 08](https://github.com/user-attachments/assets/05ab4df0-b412-4e7b-a9ab-8aa243ca8bc0)

**Your setup**
```json
    "vite": "^5.4.8",
    "vite-plugin-csp-guard": "^1.1.1",
```

 - Vite Version: 
 - React
 - SCSS

**Additional context**

Config

```js
csp({
      override:true,
      // algorithm: 'sha256', // The algorithm to use for hashing
      dev: {
        run: true, // If you want to run the plugin in `vite dev` mode
        outlierSupport: ['sass', 'scss'],
      },

      policy: {
        'base-uri': ["'self'"],
        'object-src': ["'none'"],
        'script-src': ["'self'","'unsafe-inline'"],
        'style-src': ["'self'", "'unsafe-inline'"],
        'default-src': ["'none'"],
        'frame-ancestors': ["'none'"],
        'form-action': ["'self'"],
        'manifest-src': ["'self'"],
        'frame-src': ['*'],
        'font-src': ['*'],
        'connect-src': ['*'],
        'worker-src': ['*'],
        'img-src': ['* data:'],
      },
    }),
```

**Comment by RockiRider** [comment]
@faebeee Thanks for the issue and for using the plugin! I'll get a fix for this out soon and write some tests so this doesn't happen again - cheers!

**Comment by RockiRider** [comment]
@faebeee PR for this is up, so this issue should be fixed in the next patch release.

 I noticed the `unsafe-inline` for the `script-src` in your policy, something that this plugin aims to solve.  Is there a specific/unique reason you need this? Only asking to figure out if theres anything else the plugin can do better!

**Comment by faebeee** [comment]
Thanks a lot ❤️ .

Honestly I don't now. It's kinda an old(er) app which I just started taking over. Still don't know all the parts. I just migrated vom Webpack to Vite. It was already like this in Webpack and to ensure the same behaviour I did not change it. Also we are able to inject some custom inline JS to make some modifications for clients. This surely is a risk but unfortunately it's out of my hands 🙈
